### ISSUE TITLE
cant run bootstrap: An error occurred while installing json (2.6.2), and Bundler cannot continue.

### ISSUE THREAD

**Issue by nwsparks** [benbalter/count-org-loc#6]
### Describe the bug

unable to run bootstrap, receive error `An error occurred while installing json (2.6.2), and Bundler cannot continue.`

### Steps to reproduce the behavior

follow readme instructions

**Comment by HoraceShmorace** [comment]
I can corroborate this.

```bash
$ script/bootstrap
+ brew tap Homebrew/bundle
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).

You have 29 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

+ brew bundle install
Using cloc
Homebrew Bundle complete! 1 Brewfile dependency now installed.
+ bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using public_suffix 5.0.0
Using ast 2.4.2
Using bundler 2.3.26
Using cliver 0.3.2
Using dotenv 2.8.1
Using faraday-net_http 3.0.2
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
  /Library/Ruby/Gems/2.6.0/build_info
  /Library/Ruby/Gems/2.6.0/cache
  /Library/Ruby/Gems/2.6.0/doc
  /Library/Ruby/Gems/2.6.0/extensions
  /Library/Ruby/Gems/2.6.0/gems
  /Library/Ruby/Gems/2.6.0/specifications
Using rexml 3.2.5
Using unicode-display_width 2.3.0
Using parallel 1.22.1
Using rainbow 3.1.1
Using regexp_parser 2.6.1
Using ruby-progressbar 1.11.0
Using addressable 2.8.1
Using ruby2_keywords 0.0.5
Using faraday 2.7.1
Using sawyer 0.9.2
Using parser 3.1.3.0
Using octokit 4.25.1
Using rubocop-ast 1.24.0
Installing json 2.6.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/v1/gn0dqt9j7cx73nv9t15d2spr0000gn/T/bundler20221205-34921-5pdhuajson-2.6.3/gems/json-2.6.3/ext/json/ext/generator
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20221205-34921-9ke4f2.rb extconf.rb
creating Makefile

current directory:
/private/var/folders/v1/gn0dqt9j7cx73nv9t15d2spr0000gn/T/bundler20221205-34921-5pdhuajson-2.6.3/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory:
/private/var/folders/v1/gn0dqt9j7cx73nv9t15d2spr0000gn/T/bundler20221205-34921-5pdhuajson-2.6.3/gems/json-2.6.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10:
fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10:
note: did not find header 'config.h' in framework 'ruby' (loaded from
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/var/folders/v1/gn0dqt9j7cx73nv9t15d2spr0000gn/T/bundler20221205-34921-5pdhuajson-2.6.3/gems/json-2.6.3 for inspection.
Results logged to
/var/folders/v1/gn0dqt9j7cx73nv9t15d2spr0000gn/T/bundler20221205-34921-5pdhuajson-2.6.3/extensions/universal-darwin-21/2.6.0/json-2.6.3/gem_make.out

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:51:in `block in make'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `make'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:62:in `block in
build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in
build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in
build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing json (2.6.3), and Bundler cannot continue.

In Gemfile:
  rubocop-performance was resolved to 1.15.1, which depends on
    rubocop was resolved to 1.39.0, which depends on
      json
```

**Comment by benbalter** [comment]
That error is not specific to this project. https://github.com/CocoaPods/CocoaPods/issues/10286, https://github.com/github/linguist/issues/5147, https://stackoverflow.com/questions/51263768/gem-install-fatal-error-ruby-config-h-file-not-found-in-mojave, or https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found may help resolve the issue.
